### ISSUE TITLE
ACF Gallery Field returning empty array

### ISSUE THREAD

**Issue by jonlow** [wp-graphql/wp-graphql-acf#224] opened 2021-01-27 23:51 UTC
I'm using `gatsby-source-wordpress-experimenta` and my ACF gallery field is returning an empty array even if there is data in it (Note the data is not null, but an empty array). More details can be found in this issue 
https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/issues/422

I've stepped through the debugging steps and the `node-list-query.graphql` query returns the data correctly when I use my altair graphql client. The docs suggest that this is an issue on the wpgraphql side and not the `gatsby-source-wordpress-experimental` site https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/debugging-and-troubleshooting.md 

At time of this post my plugins are pretty up to date. Let me know if there is anything else I can provide.

Plugin versions below

Gatsby
"gatsby-source-wordpress-experimental": "7.0.3",

Wordpress
"gatsbyjs/wp-gatsby": "0.9.2",
"wp-graphql/wp-graphql-acf": "0.4.0",
"wp-graphql/wp-graphql": "1.1.2",

**Comment by jasonbahl** [comment] 2021-03-05 21:33
@jonlow If the query is working in Altair as you stated, but not in Gatsby Source WordPress, this leads me to believe the issue is not related to WPGraphQL / WPGraphQL ACF, but actually `gatsby-source-wordpress`. 

Can you provide screenshots of what you're seeing as output in Altair and why you think this is an issue with WPGraphQL / WPGraphQL for ACF and not the source plugin?

Also, if you can provide details on what data is stored in the ACF meta for the gallery field, that might be helpful as well. Like does the issue occur when certain image IDs are saved, when nothing is saved, etc?

**Comment by jonlow** [comment] 2021-03-06 02:59
hey @jasonbahl I'm actually convinced it's an issue with `gatsby-source-wordpress` but Tyler told me to check-in here haha. To get the bills paid we'd just rolled our own custom gallery field ☝️ but I'll provide more info when I run into it on the project again.

**Comment by jasonbahl** [comment] 2021-03-26 22:05
@jonlow I'm going to close this issue for now. If it pops up again, and is possible to reproduce in WPGraphQL (aside from sourcing in Gatsby) then open a new issue with steps to reproduce and we can look into it further.

**Closed as completed by jasonbahl** 2021-03-26 22:05 UTC
Labels: status: awaiting author response, Needs to be reproduced
