### ISSUE TITLE
Both WPGraphQL (v0.4.0+) and Advanced Custom Fields (v5.7+) must be active for "wp-graphql-acf" to work

### ISSUE THREAD

**Issue by leobar37** [wp-graphql/wp-graphql-acf#212] opened 2021-02-04 14:41 UTC
Hi, I have this error,
the plugin worked fine the first time, this error occurred after installing the following plugin

[Custom Post Type UI](https://wordpress.org/plugins/custom-post-type-ui/)

After uninstalling it, it does not work again

**Comment by jasonbahl** [comment] 2021-02-05 08:16
@leobar37 can you share what versions of the following you were running when you saw this error?

- PHP
- WordPress
- WPGraphQL
- WPGraphQL for ACF
- WPGraphQL for Custom Post Type UI
- Advanced Custom Fields
- Custom Post Type UI

Also, any other plugins and their versions would help. 

And where did you see this error? Screenshot would be helpful.

**Comment by leobar37** [comment] 2021-02-05 13:40
Yes, thanks for answering

WP GraphQL ---> Version 1.1.3 
WPGraphQL for Advanced Custom Fields ---> Version 0.4.1
Custom Post Type UI ---> Version 1.8.2
wordpress ---->  5.6.1
PHP version --> 7.4.14

**Comment by leobar37** [comment] 2021-02-05 13:42
![image](https://user-images.githubusercontent.com/60113294/107041045-04e3ff80-678e-11eb-8690-faf2e98832d5.png)

**Comment by ChristopherNowlan** [comment] 2021-02-15 05:11
Advanced Custom Fields doesn't appear to be installed in the screenshot @jasonbahl

**Comment by rsm0128** [comment] 2021-02-27 07:24
It's not a bug with this plugin. He didn't install ACF. The error message and the screenshot obviously says that.

**Comment by jasonbahl** [comment] 2021-02-28 19:58
Closing as it appears ACF is not installed as other have said as well

**Closed as completed by jasonbahl** 2021-02-28 19:58 UTC
Labels: status: awaiting author response
