### ISSUE TITLE
If repeater image field is empty, throws internal server error

### ISSUE THREAD

**Issue by drewbaker** [wp-graphql/wp-graphql-acf#63] opened 2019-09-19 01:54 UTC
I was trying to query a repeater field that had a title and an image. If the image was empty, then it would error.

```
            headerGallery {
                text
                image {
                    id
                }
            }
```

If `image` is not set in the CMS, this will return an `internal server error`.

**Comment by jydmnd** [comment] 2019-10-20 18:45
I was not able to reproduce your bug. I created a new ACF for Posts, with a repeater containing a text field and an image. I didn't set an image, only the title, and the GraphQL query returned _null_ for the image.

**Comment by drewbaker** [comment] 2019-10-20 18:50
Some time has passed and I think we’ve ran into this error more now and it actually has to do with a repeater or a post object field that has multiple types allowed. So you’d need to do ... on Post {} or ... on Page {}, and if you don’t set one of those unions, it will give you an error. Maybe that’s how it’s supposed to be?

**Comment by benleeth** [comment] 2020-03-30 17:13
Has anyone found a solution for this?
Using GraphiQL App.
URL: https://designpickle2s.wpengine.com/graphql?query
Query:
```
{
  thankYouPage(id: "dGhhbmsteW91LXBhZ2U6ODgxODE=") {
    title
      design_pickle_modules {
        modules {
          ... on ThankYouPage_DesignPickleModules_Modules_TwoColumn {
            columns {
              buttons {
                calendlyUrl
                linkStyle
                linkType
                text
                url
                wistiaVideoId
              }
              content
              image {
                sourceUrl
                altText
                mimeType
                imageFile {
                  publicURL
                }
              }
              lightdark
              title
            }
          }
        }
      }
    }
  }}
```
Returns:
```
{
  "errors": [
    {
      "message": "Cannot query field \"imageFile\" on type \"MediaItem\".",
      "category": "graphql",
      "locations": [
        {
          "line": 21,
          "column": 17
        }
      ]
    }
  ]
}
```
But if I remove `image` from the query:
```
{
  thankYouPage(id: "dGhhbmsteW91LXBhZ2U6ODgxODE=") {
  	title
      design_pickle_modules {
        modules {
	  ... on ThankYouPage_DesignPickleModules_Modules_TwoColumn {
            columns {
              buttons {
                calendlyUrl
                linkStyle
                linkType
                text
                url
                wistiaVideoId
              }
              content
              lightdark
              title
            }
          }
        }
      }
    }
  }
```
Everything returns correctly.

The issue is the image for the second column is blank.

**Comment by jasonbahl** [comment] 2021-05-14 19:19
@drewbaker I did (finally, after all this time 🤦🏻‍♂️) try and reproduce and was not able to.

My guess is that this issue is no longer relevant based on the time that's passed and changes that have happened in the plugin in that time. 

Anyway, here's the steps I took. 

## Create Field Group

I created a field group field to match what you described

- Field of the Group field type named "header_gallery" 
  - Text field named "text"
  - Image field named "image"

 ![Screen Shot 2021-05-14 at 1 04 16 PM](https://user-images.githubusercontent.com/1260765/118317119-e55b2200-b4b4-11eb-83df-711e131a45e0.png)

## Query fields

### v0.5.2

Then, without updating a post, leaving the image field unset, I queried for these fields, like so: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    postTest {
      headerGallery {
        text
        image {
          sourceUrl
        }
      }
    }
  }
}
```

I get a null response, without errors, as I would expect for a post that didn't have these fields populated. 

![Screen Shot 2021-05-14 at 1 12 17 PM](https://user-images.githubusercontent.com/1260765/118318003-02dcbb80-b4b6-11eb-88c4-5ecaffc5a079.png)

I can edit the post, adding a value to the text field, but leaving the image field empty, and still get the data, but no errors:

![Screen Shot 2021-05-14 at 1 16 28 PM](https://user-images.githubusercontent.com/1260765/118318422-9ca46880-b4b6-11eb-9db6-fe07834e46fc.png)

### v0.6.0

In v0.6.0 (#262) the shape of the query is a bit different, but getting a null response and no errors is still the behavior: 

```graphql
{
  post(id: 2179, idType: DATABASE_ID) {
    id
    postTest {
      headerGallery {
        text
        image {
          node {
            sourceUrl
          }
        }
      }
    }
  }
}
```

![Screen Shot 2021-05-14 at 1 18 08 PM](https://user-images.githubusercontent.com/1260765/118318597-d5444200-b4b6-11eb-9588-b3d548eeb0a5.png)

**Comment by jasonbahl** [comment] 2021-05-14 19:22
@benleeth As it's been so long since this issue got attention, I'm not sure if you're still having issues. 

If you are, please open a new issue with steps to reproduce. 

Based on the error you were seeing, it seems to me like you were trying to query fields that didn't exist in the Schema. 

My guess is that maybe you had tried to add an ACF Field Group to Media Items, then tried to query the fields on the Image? 

If so, that _should_ be working now. The [v0.5.0 release](https://github.com/wp-graphql/wp-graphql-acf/releases/tag/v0.5.0) made a lot of improvements to location rules and how ACF Field Groups can be assigned to the GraphQL Schema. 

I'm going to close this, but if you are still running into issues, please let us know and provide as many steps to reproduce as possible. 

Thanks!

**Closed as completed by jasonbahl** 2021-05-14 19:22 UTC
Labels: bug, Needs to be reproduced

**Comment by drewbaker** [comment] 2021-05-14 19:30
Thanks for looking, I haven’t run into this in a long time. I think it got fixed along the way. Thanks.
