### ISSUE TITLE
Post Objects in Repeater don't provide access to ACF fields on those objects

### ISSUE THREAD

**Issue by philiphetue** [wp-graphql/wp-graphql-acf#112] opened 2020-03-06 00:19 UTC
I'm very new to GraphQL, so I apologize if this is simply my own lack of understanding. But, meta fields that I've verified are available via a direct query to the objects are _not_ available when accessing those same objects through a Repeater of Post Object fields. Will I have to do separate queries to get post ids first, then query those objects directly? Thank you!

**Comment by jasonbahl** [comment] 2020-03-11 18:57
@philiphetue can you provide a reproducible example so I can replicate? 

Anywhere you can access a Post, you should be able to access the Post's fields, whether it's at the Root of the Graph or within a Repeater field. 

Can you share examples of queries you're running where this doesn't seem to be the behavior?

**Comment by gedeminas** [comment] 2020-03-23 11:02
@philiphetue I had same problem with 0.3.1, try using development branch, works for me

**Comment by jasonbahl** [comment] 2020-03-23 15:17
@gedeminas can you share examples of queries that didn't work on v0.3.1 that do work now? 

I'd like to add tests to make sure I don't cause this behavior again.

**Comment by foltra** [comment] 2020-03-31 22:20
I had a similar issue, in my case the fields linked to a post object of custom post type. 
I just had to add these fields when registering them:
```
[
   'show_in_graphql' => true,
    'hierarchical' => true,
     'graphql_single_name' => 'Venue',
     'graphql_plural_name' => 'Venues',
]
```

Hope this helps

**Comment by jasonbahl** [comment] 2020-03-31 22:53
I'm having trouble understanding this issue. I've asked for a [reproducible example](https://github.com/wp-graphql/wp-graphql-acf/issues/112#issuecomment-597810342) and [examples](https://github.com/wp-graphql/wp-graphql-acf/issues/112#issuecomment-602666684). Without some added context here, I'm not sure I can offer assistance. 

Perhaps @foltra's suggestion to make sure your Post Types are set to `show_in_graphql` is the solution? With more context I could confirm or provide more insight. 

Closing as this isn't actionable. Can re-open if more context is provided.

**Closed as completed by jasonbahl** 2020-03-31 22:53 UTC
Labels: status: awaiting author response, Needs to be reproduced, Needs Info
