### ISSUE TITLE
ACF not showing when rule is set to user role

### ISSUE THREAD

**Issue by jydmnd** [wp-graphql/wp-graphql-acf#58] opened 2019-09-09 20:05 UTC
When creating an ACF and setting the rules as:
**Show this field group if**:
**User role is equal to _ROLE_**
The ACF field isn't queryable through the viewer (when authenticated). Here is an example query :

```graphql
query getViewer {
  viewer {
    id
    username
    name
    userId
    myacf
  }
}
```

This returns this error : 
```json
{
  "errors": [
    {
      "message": "Cannot query field \"myacf\" on type \"User\".",
      "category": "graphql",
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ]
    }
  ]
}
```

It works when the rule is set as _User role is equal to All_, but will show on every user profile, which is not ideal.

**Comment by jasonbahl** [comment] 2019-09-09 20:20
Hey @jydmnd! 

Thanks for reporting this. This ACF "location rule" is not yet supported. 

For context, should anyone come across this: 

The GraphQL Schema is independent of any context, such as the user's role, for example. The Schema is representation of what's possible (what _can_ be asked for), and Resolvers take into consideration context (such as the current user, or a specific object being resolved) when resolving the info. . .but in ACF, there is context, because you're loading a specific admin page to interact with the fields.

Mapping contextual rules from ACF Field Groups, such as a specific page or a specific user role, gets tricky, because the GraphQL Schema is the same Schema regardless of resolve context
so adding support for those contextual locations has been tricky to say the least. 

----

This is a location I think we _should_ support. 

The way I see it working would be that the fields should be added to the User Type. 

This way, the fields can be asked for anytime a user is asked for. During resolution, the user role can be checked, and if the user has the assigned capability, the fields will resolve. If the user doesn't have the assigned capability, the field group will return `null`.

**Comment by jasonbahl** [comment] 2021-04-20 22:27
👋🏻  Sorry for the delay on this, but this has been fixed! 

With v0.5.0 (#250) you can use the `User Role` rule and the field group will be mapped to the Schema. 

Below is a screenshot of this rule in action, and the new UI where you can opt-in to manually overriding how it is auto-mapped if needed. 

![Screen Shot 2021-04-20 at 4 26 25 PM](https://user-images.githubusercontent.com/1260765/115471404-284b1200-a1f5-11eb-9f41-05f02962b5e9.png)

**Closed as completed by jasonbahl** 2021-04-20 22:27 UTC
Labels: enhancement, good first issue, :rocket: Actionable, New Feature

**Comment by jakubszynklarz** [comment] 2021-05-28 08:06
Hi @jasonbahl, 
I have the same problem. The fields I create should be displayed for every user, regardless of their role. Unfortunately, you can't see the "author's site" field group in GrapQL Schema. I am asking for help and information on what I am doing wrong.

WPGraphQL version 1.3.5
WPGraphQL for Advanced Custom Fields version 0.4.1

![acf](https://user-images.githubusercontent.com/37659619/119950960-b99f6800-bf9b-11eb-8cb8-c509925af4a1.png)
![viewer](https://user-images.githubusercontent.com/37659619/119950982-c02ddf80-bf9b-11eb-9bd1-0cb51d3b7947.png)
![user](https://user-images.githubusercontent.com/37659619/119950993-c3c16680-bf9b-11eb-966d-9490fcf7f712.png)

**Comment by jakubszynklarz** [comment] 2021-06-01 13:47
I updated the plugin to version 0.5.2 and the problem is fixed
