### ISSUE TITLE
Flexible Content with empty Layout breaks the plugin 

### ISSUE THREAD

**Issue by danieelito** [wp-graphql/wp-graphql-acf#150] opened 2020-06-28 00:28 UTC
I don't have any specifics, just that, if you create a Flexible Content block, and inside there is a Layout empty, the plugin breaks.

**Comment by idflood** [comment] 2020-11-06 15:38
Thanks, I was having a hard time finding why the plugin broke.

Note that if it might help one use case is to create a "Latest news" layout which would have no option since everything is handled on the frontend. This is useful to move this block in any place of a website for example.

**Comment by jasonbahl** [comment] 2023-11-07 21:41
duplicate of: #106

**Closed as completed by jasonbahl** 2023-11-07 21:41 UTC
Labels: Needs to be reproduced, Field Type: Flex
