### ISSUE TITLE
Troubleshooting taxonomy field in flexible content

### ISSUE THREAD

**Issue by StudioEvolDev** [wp-graphql/wp-graphql-acf#380] opened 2024-02-13 08:24 UTC
Hello,

I have an option page with a flexible content ACF field. In each RowLayout, I have a taxonomy field that targets a specific custom taxonomy. My query always returns an uncategorized term with databaseId : 1

WPGraphQL version : 1.21.0
WPGraphQL for ACF version: 2.1.1

**Comment by jasonbahl** [comment] 2024-02-28 18:11
@StudioEvolDev since you're using WPGraphQL for ACF v2+, can you [open an issue on the new repo](https://github.com/wp-graphql/wpgraphql-acf/issues/new?assignees=&labels=&projects=&template=bug_report.yml), and follow the issue template to provide information that can help us reproduce, etc?

I'm going to close this, and keep an eye out for the new issue on the new repo with the added reproduction details.

Thanks! 🙏🏻

**Closed as completed by jasonbahl** 2024-02-28 18:11 UTC
