### ISSUE TITLE
Layout sub fields in Flexible Content field type returning 'null'

### ISSUE THREAD

**Issue by hamiltonbrooke** [wp-graphql/wp-graphql-acf#353] opened 2023-04-04 09:54 UTC
When querying flexible content field types in GraphiQL on Localhost, the sub fields in each of the layouts are returning 'null'.

When querying flexible content field types in GraphiQL IDE on my WordPress install, the sub fields in each of the layouts are returning the correct data.

I duplicated and renamed a 'Field Group' in ACF and assigned it to a new page.
This is the page the GraphQL query issues are occurring on.
Is it something to do with this?!?

**Comment by GrowthWizard** [comment] 2023-06-22 16:17
I recently run into the same issue, allthough I couldn't pin down, why the issue is caused.
It only seems to appear with duplicated field groups.

**Comment by jasonbahl** [comment] 2023-07-07 22:25
Hey, this plugin is actively being re-built over here: https://github.com/wp-graphql/wpgraphql-acf. 

It's getting close to a stable release on the WordPress.org repo. There were a lot of bugs related to Flexible Content fields that have been addressed in the new version. 

If possible, we'd recommend updating to that version and reporting any issues you have with it on that repo. 

Docs and upgrade guide are in the works, but that's the version of the plugin we'll be supporting going forward. 🙏🏻

**Closed as completed by jasonbahl** 2023-07-07 22:25 UTC
