### ISSUE TITLE
gatsby-source-wordpress Request failed 

### ISSUE THREAD

**Issue by cnmarinas** [wp-graphql/wp-graphql-acf#348] opened 2023-01-27 23:11 UTC
Hi, we are using gatsby-source-wordpress to fetch contents. We had intermittent "gatsby-source-wordpress  Request failed with status code 500" error in the past, but usually if we triggered another build will be fine. But recently the build always failed with the request failed message. We tried to see the Apache log, and it shows this:

```
Got error 'PHP message: PHP Fatal error:  Out of memory (allocated 39845888) (tried to allocate 20480 bytes) in /bitnami/wordpress/wp-content/plugins/wp-graphql-acf-master/src/class-config.php on line 550     
PHP message: PHP Fatal error:  Out of memory (allocated 39845888) (tried to allocate 20480 bytes) in /opt/bitnami/wordpress/wp-includes/class-wp-fatal-error-handler.php on line 74
```

```
PHP message: PHP Fatal error:  Out of memory (allocated 6291456) (tried to allocate 20480 bytes) in /bitnami/wordpress/wp-content/plugins/wp-graphql-acf-master/src/class-config.php on line 1083
PHP message: PHP Fatal error:  Out of memory (allocated 6291456) (tried to allocate 20480 bytes) in /opt/bitnami/wordpress/wp-includes/class-wp-fatal-error-handler.php on line 74'
```

We had recently upgraded to WordPress 6.1.1, and the plugins versions are:

Advanced Custom Fields PRO: 6.0.7
WP GraphQL: 1.12.2
WPGraphQL for Advanced Custom Fields: 0.6.1

The server only has 4 GB RAM, but it worked for two years until recently we upgraded to WordPress 6.1 (was 5.9) and above plugin upgrade. Could the problem be the WordPress upgrade or the ACF plugin upgrade?

It can be memory leak issue, since when it crashes (Request failed), the memory usage in the "WordPress server" **_stays_**.

We would really appreciate it if you could help or shed some light on this.

**Comment by jasonbahl** [comment] 2023-07-07 22:36
I believe this issue _might_ have been caused by a regression in core WPGraphQL that's since been resolved. Going to close this, but if it's still an issue, open a new issue with as many details as possible so we can reproduce. 

Also, we'd recommend checking out the new version of WPGraphQL for ACF over here: https://github.com/wp-graphql/wpgraphql-acf as it will be released on WordPress.org soon and is the version of the plugin we'll be supporting long-term, archiving this one in the not-too-distant future

**Closed as completed by jasonbahl** 2023-07-07 22:36 UTC
